language: bash
services: docker

version:
  - 1.0
  - 2.0

jobs:
  include:
    - stage: build1-1.0
      version: 1.0
      script: echo build1 1.0
      if: commit_message ~/(^.*\[build1.0\].*$)/
    - stage: build1-2.0
      version: 1.0
      script: echo build1 2.0
      if: commit_message /(^.*\[build2.0\].*$)/
    - stage: build2
      script: echo build2
      if: commit_message ~/(^.*\[build2\].*$)/
